version: 2
jobs:
  build:
    working_directory: ~/ProductCatalog_lab
    docker:
      - image: cimg/android:2023.11.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
         name: Chmod permissions  
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run UnitTest
          command: ./gradlew test
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks/
      - store_test_results:
          path: app/build/test-results